### ISSUE TITLE
Sponsors Page

### ISSUE THREAD

**Issue by hreeder** [compsoc-edinburgh/website2016#3]
Sponsors page needs creating and populating.

Maybe someone from the committee could at least give input as to what to put on the page?

**Comment by neanias** [comment]
@JoshGreen1337 Can you get the sponsors for this, please?

**Comment by Josh-00FF00** [comment]
Sure, although the current list isn't complete especially since this year it's a tiered system similar to the HTB site. I'll try and get a list tho

**Comment by qaisjp** [comment]
done in #11
