### ISSUE TITLE
Home Page Twitter & Facebook Latest Posts

### ISSUE THREAD

**Issue by hreeder** [compsoc-edinburgh/website2016#5]
Home page could do with a feed of twitter and facebook.

I'll tackle this.

**Comment by hreeder** [comment]
Added this in 7edbd87, this is how it looks currently
![2016-09-15-191205_1366x768_scrot](https://cloud.githubusercontent.com/assets/601246/18561565/5b1fa9a0-7b78-11e6-8b65-ad844b45828e.png)

**Comment by neanias** [comment]
👍
